apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-dados
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    request:
      storage: 5Gi
  storageClassName: standard=rwo

---
apiVersion: apps/v1
kind: Deployment
metedata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
      spec:
        containers:
          - name: mysql
            image: leandz9/projeto-database:1.0
            args:
            - "--ignore-db-dir-lost+found"
            imagePullPolicy: Always
            ports:
              - containerPort: 3306

            volumeMounts:
              - name: mysql-dados
                mountPath: /var/lib/mysql
        volumes:
          - name: mysql-dados
            persistentVolumeClaim:
              claimName: mysql-dados
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    app: php
spec:
  replicas: 6
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
        - name: php
          image: leandz9/projeto-backend:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"